### ISSUE TITLE
Modifications are not properly monitored

### ISSUE THREAD

**Issue by BrianisBlack** [BSData/star-wars-armada#1]
There's nothing currently in the code to prevent an invalid list including ships that have multiple modifications on them (ships are limited to one modification apiece, regardless of what slot it otherwise fills).

**Comment by KealL** [comment]
Hey guys great job. Not looked at the code to see how you've done the upgrades so don't know if you can put said restriction on. But in the mean time could we have something in the upgrade card's name to tell you it's a mod. As I must admit I've fallen foul of this a few times when making lists on the fly. Maybe just an M or Mod

Enhanced Armament - M
Enhanced Armament - Mod

**Comment by KealL** [comment]
I have dealt with this except for the issue where you can select two of the same items from a list such as the ISD1 with two offensive upgrade slots, so it cannot currently prevent you taking two Tractor Beams

**Comment by BrianisBlack** [comment]
Nice, thanks!  I'm going to have to look to see how you implemented this, because it was driving me crazy!

**Comment by KealL** [comment]
i've put a set of conditions hiding each modification if any other modification is already present. The way to over come the duplicates as with the same upgrade slot ISD offensive slots and MC0 Defensive slots would be to have two groups for those slots where one hides its mod if the other had a mod. But I did not wish to make such a change without discussing it with those of you that have done most of the work first. If you are happy for me to do this I will gladly do it. It will just mean whenever a new ship comes out with two of the same slots it will need a second group for the second slot. Also when a new modification comes out they will need adding to the conditions as needing to cause them to hide etc. but I don't mind doing this when new waves come out.

**Comment by BrianisBlack** [comment]
1- Sorry for my delayed response to your messages, I've been off github for a month and a half so I didn't see your messages.2- Thank you so much for doing this!  I had been grinding on this for a couple months earlier last year trying to implement that rule!  I'd say go ahead and put it in for the ISD offensive and MC80 defensive slots if you haven't already. 

    On Friday, January 15, 2016 6:02 PM, KealL <notifications@github.com> wrote:
 

 i've put a set of conditions hiding each modification if any other modification is already present. The way to over come the duplicates as with the same upgrade slot ISD offensive slots and MC0 Defensive slots would be to have two groups for those slots where one hides its mod if the other had a mod. But I did not wish to make such a change without discussing it with those of you that have done most of the work first. If you are happy for me to do this I will gladly do it. It will just mean whenever a new ship comes out with two of the same slots it will need a second group for the second slot. Also when a new modification comes out they will need adding to the conditions as needing to cause them to hide etc. but I don't mind doing this when new waves come out.—
