### ISSUE TITLE
Commander validation

### ISSUE THREAD

**Issue by C77out** [BSData/star-wars-armada#11]
When generating a list, the following errors for Imperial or Rebel

You must have at least 1 selections from Commander in your Roster.

This error occurs three times.

To test issue
Create list <imperial 300 pts>
Add Victory II 
Add Motti to Commander Slot
Add the three Objective Types

Check validation errors

**Comment by BrianisBlack** [comment]
I'm getting different validation messages:
- Roster has 2 too many selections of Admiral Motti (maximum of 1)
- Roster has 2 too many selections from Commander (maximum of 1)

This is on iOS, and both those errors sound correct. What version of battlescribe are you using?

**Comment by C77out** [comment]
I am using Battlescribe 1.14 on Android
I tried another device with Battlescribe 1.15 on Android and do not get this issue.
Looks like the update may resolve the issue , Going to try updating the other device once it is in my possession again

**Comment by BrianisBlack** [comment]
Sounds good.  If it's still an issue, post here and I'll elevate it to the battlescribe dev.

**Comment by BrianisBlack** [comment]
Going to close this issue, if this resurfaces, please reopen or create a new issue.
