### ISSUE TITLE
Differentiate Factions between Armada and X-Wing files

### ISSUE THREAD

**Issue by BrianisBlack** [BSData/star-wars-armada#12]
Both the xwing and armada files make use of "Imperial" and "Rebel Alliance" for their force nomenclature. By changing them to "Imperial Navy" and "Rebel Fleet" respectively, it will be easier to distinguish lists for the two lines when they are compiled into one list (in the iPhone app, for exampe).

**Comment by XWingDrLucky** [comment]
Good idea!
