### ISSUE TITLE
Speed Charts

### ISSUE THREAD

**Issue by BrianisBlack** [BSData/star-wars-armada#2]
Speed Charts are not included as part of the ship basic stats.  I'm not really sure how to add these, as they kinda require a chart to display properly.

**Comment by KealL** [comment]
We could implement this as a table, using a profile?

E.g.

Ship                       Notch 1          Notch 2         Notch 3         Notch 4
ISD-Speed01            1                      NA                  NA                NA
ISD-Speed02            1                       1                    NA                NA
ISD-Speed03            0                       1                      1                 NA

Thoughts?

**Comment by vadersson** [comment]
I will keep this open and see what I can do.  I have added a maximum speed stat to all ships to at least give some input.

**Comment by BlueSeven** [comment]
Speed charts added in 1.7.0.
