### ISSUE TITLE
Assault Proton Torpedoes

### ISSUE THREAD

**Issue by Boston1809** [BSData/star-wars-armada#22]
This is the dumbest thing in the world, but it's been driving me nuts. If you add Assault Proton Torpedoes to a ship, when you go to view the roster (with the eyeball icon) it calls them Assault Concussion Missiles. It has the correct points and description of effect, it just calls the ACMs. All we have to do to change that is to go into the Shared Selection Entry Groups -> Assault Proton Torpedoes section and in the subcategory they're called Assault Concussion Missiles, which is what's displayed with the view feature in the app. It needs to be fixed for both the Rebel and the Imperial files I believe. I'd do it myself, but I'd have to make a pull request and I'm not 100% sure that a correction this slight is worth versioning the whole project. Thank you all so much for all the work on this project!

**Comment by KealL** [comment]
Done.
Update will be seen next time a release is issued
