### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by abc** [BSData/star-wars-armada#24]
Hey there, I would like to help out with this project. Would you kindly add me as a developer so I can commit my changes?

Thank you. 

Alastair.

**Comment by amis92** [comment]
Hello, @abc. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also for some help check out a quite active 40k Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!
