### ISSUE TITLE
Squadron Organization in the Menu

### ISSUE THREAD

**Issue by XWingDrLucky** [BSData/star-wars-armada#29]
Especially with the new squadrons released in the Corellian Conflict, the list of squadrons is getting pretty big and unwieldy when creating a roster.  Particularly for people who might not remember all the cards off the top of their head, it's getting to be a little rough on the organization side.  I think it would really help to organize by ship type.

How do people feel about changing this?  Here's what I propose:

I built some dummy catalogue entries looking for the best way to do this and the one I came up with that seems to work the best and look the best is to create roster level selections of squadron-types.  On the main selection menu, listed under Squadrons, the user would see "A-Wing Squadrons", "B-Wing Squadrons", etc.  Those actual entries have no profile associated with them, just an entry group with the various options.  So if the user selected "X-Wing Squadrons" they would get a menu allowing them to add any number of copies of the generic "X-Wing Squadron" plus checkboxes allowing them to select singletons of each unique: "Rogue Squadron", "Luke Skywalker", "Biggs Darklighter", and "Wedge Antilles".  Each of those selections would be linked to a profile, as usual, so the display of squadron profiles in the Roster View wouldn't change (However, all your X-Wing squadrons would be grouped together at the top of the Roster View).

The only downside to this is that all the squadron keywords for each ship type would get displayed together (which could get confusing when different squadrons have different keywords).  For instance, if you had one generic X-Wing Squadron and Rogue Squadron, the rules displayed would be Bomber, Escort, and Rogue (since the generic squadron has the Bomber and Escort Keywords while Rogue Squadron has the Bomber and Rogue keywords).  This is easily resolved by adding a Keyword field to the Squadron profile template (the rules would still remain as having the rules text is really helpful).

Any thoughts on this?  I don't mind doing the revisions and I could handle them this weekend (along with adding the last of the new Corellian Conflict squadrons into the catalogues).  It's a big enough change that I didn't want to just do it without consulting those of you who've been maintaining these files for some time, but I do think it is the right move.

**Comment by BlueSeven** [comment]
something like this is probably a good idea. also maybe move the squadrons
to either the start or end along with the objectives as its all jumbled up
right now?

**Comment by XWingDrLucky** [comment]
Actually, I already moved Squadrons and Objectives to the end in the release a few days ago. You may not have seen it yet if you haven't updated your data recently. I'm glad we're one the same wavelength.

**Comment by JJsJuggernaut** [comment]
I also really like this idea.

**Comment by KealL** [comment]
Thumbs up

**Comment by XWingDrLucky** [comment]
I'll take care of it in the next day or two. I'll add the last few CCA
cards while I'm at it.

**Comment by XWingDrLucky** [comment]
Done.  Let me know what you all think.
