### ISSUE TITLE
Squadron Points are rounding down at 33% of list points

### ISSUE THREAD

**Issue by BrianisBlack** [BSData/star-wars-armada#3]
Attempting to set the Game System Max Percentage for Squadrons at 33 throws errors on a 300 point list above 99 squadron points, when it should be going to 100.  Currently, the system is hard set to 100 points of squadrons before throwing a flag, as following the release of wave 1, the default list size will be 300 points.

**Comment by BrianisBlack** [comment]
Suggested fix to try was to put in a modifier that increments the squadron limit by one for every three points in the fleet limit. Will give this a try the next time I've got a free evening.

**Comment by BrianisBlack** [comment]
Tested the modifier route, but it's not incrementing correctly- it only increases the maxPoints limit from 0 to 1 regardless of the number of points for the roster.

**Comment by KealL** [comment]
#Close
