### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by JJsJuggernaut** [BSData/star-wars-armada#31]
I use the free battlescribe app for iOs. Ever since the last two updates, whenever I try to add a force to the roster is crashes out of the app. Another person or two mentioned the crashes on the FFG forums. I'm not sure if it's an issue with the files, battlescribe, or just certain hardware. I just figured I'd throw this here as well. If you need any information I'll do my best to answer any questions.

**Comment by KealL** [comment]
Currently not able to duplicate. Can you update the app and then check for new data and see if this persists

**Comment by JJsJuggernaut** [comment]
I discovered the issue. I was assuming the app was up to date since I checked for updates to it several times, as well as for new data; I appear to have missed the fact that the 2.0 version is an entirely different app that I needed to download.
