### ISSUE TITLE
Order of sections

### ISSUE THREAD

**Issue by HippySi** [BSData/star-wars-armada#4]
First of thanks, for your excellent work on this so far. Any chance of changing the order the sections are displayed in?

I think a more logical order would be:

Ships first in alphabetical order
Squadrons under ships
Objectives at the bottom.

**Comment by BrianisBlack** [comment]
I'm not entirely sure how things are ordered in there by default... I'll look to see what others are doing for ordering.

**Comment by BrianisBlack** [comment]
Alright, so it's editing the xml to get the ordering of the categories in the .gst.  Currently looking at how to do that so that I don't accidentally overwrite it the next time I make changes.

**Comment by BrianisBlack** [comment]
And after making a hash of commits/reverts, it's still not doing what I want.  Going to look into this further.

**Comment by XWingDrLucky** [comment]
If you based the files on my X-Wing files,  I know how to re-order them.  I'll take a crack at it when I get to my desktop and let you know what to do if it works the way i think it will.

**Comment by XWingDrLucky** [comment]
I fixed it.  I still owe you an explanation of how though.

**Comment by XWingDrLucky** [comment]
Does GitHub completely lack a PM system?  I was going to PM you an explanation but I can't seem to do so.

**Comment by amis92** [comment]
Indeed. It's rather a development/source control platform. For chit chat, I suggest you use Gitter. Very convenient, and provides PM (on condition both of you log in, but it uses GitHub to log, so no problem).

**Comment by BlueSeven** [comment]
Could I get a copy of the explanation too please?

**Comment by amis92** [comment]
So here it goes. https://gitter.im/BSData/star-wars-armada Also, I've put the link to Gitter in README.

**Comment by BrianisBlack** [comment]
That's funny DrLucky, as I saw you were online last night and was looking for a PM/IM option to ask you about this. 

You're also correct in that I used your files as a framework to build off of- they helped me avoid one of the pitfalls that I had created for myself when I initially started working on the armada files (making upgrades as linked entities instead of recreating them individually for each ship).
