### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by vadersson** [BSData/star-wars-armada#40]
Hi gang,

I see that the Armada module has not been updated since 09/2019 and with the 1.5 rules and clone wars coming out I have been trying to update the data files.  Now I need to learn how to share them.  Hopefully I can join the team and help get Armada updated.

Thanks,
Duncan
vadersson

**Comment by XWingDrLucky** [comment]
I've been way too busy to maintain all three Star Wars repos so I've been focusing on Legion.  If you want to jump in on Armada, you are absolutely welcome to.  If you've got any questions on the structure or approach of what's come before I'm happy to talk with you about it.

However, I don't think I can actually add you to the data authors here.  I think you need to make your Join Request on the organizational repo - it's the one called BSData.

**Comment by vadersson** [comment]
Ok, Ill give it a try and see if that works.  Glad to work with you.

**Comment by amis92** [comment]
@XWingDrLucky it's actually here (the correct place). BSData/bsdata is for AppSpot webapp development. For all other "organizational" issues there's BSData/catalogue-development.

**Comment by amis92** [comment]
@vadersson you've been invited: https://github.com/BSData/star-wars-armada/invitations

**Comment by vadersson** [comment]
Hey Dr. Lucky,

So I  tried to do a release of the preliminary Clone Wars armada stuff today, but I don't think it worked.  How to I actually publish updated modules?  In this case, there were a lot of changes too.  I added and deleted files in the repository, so maybe that makes it harder.  Any help you can offer?

Thanks,
Duncan

________________________________

**Comment by XWingDrLucky** [comment]
You've got to start with a synched up repo, make your changes in the synched folder, and then resynch in your GitHub client to push the files.

I'll email you directly.
