### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by BlueSeven** [BSData/star-wars-armada#43]
Have updated in a local copy:
Completed / corrected clone wars wave 2 data
Added Rapid Reinforcements 1
Added limit for unique squads with defense tokens at 1 per 100pts
Added "Tournament" force type with restriction of 2 flotillas per list
Added remaining campaign objectives
Added a version of speed charts using a profile to display a row for each joint. There is no table outline so it may need some [blank] character to aid clarity. also due to the way profile tables lay out, the speed numbers are at the top instead of below the chart.
The chart is displayed as a table below the table of ship stats, before any upgrades.

**Comment by BlueSeven** [comment]
Hi,
Thanks. Is there any update on fixing this?

**Comment by Mad-Spy** [comment]
Sorry for the delay.
